name: Claim Crates

on:
  push:
    branches:
      - master

jobs:
  claim-crates:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Rust Cache
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          cache-on-failure: true

      - name: install parity-publish
        run: cargo install parity-publish@0.5.1

      - name: parity-publish claim
        env:
          PARITY_PUBLISH_CRATESIO_TOKEN: ${{ secrets.CRATESIO_PUBLISH_CLAIM_TOKEN }}
        run: parity-publish --color always claim
